version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=False
      - SECRET_KEY=change_this_in_production
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=openrouter_proxy
      - APP_HOSTNAME=https://myapp.com
      - APP_TITLE=MyApp
      - OPENROUTER_PROVISION_KEY=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
      - ENCRYPTION_KEY=your_encryption_key_here
    depends_on:
      - db
    restart: always
    
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=openrouter_proxy
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    
volumes:
  mysql_data:
